### ISSUE TITLE
Bee Ban Board

### ISSUE THREAD

**Issue by jsug9** [jsug9/bee-bookings-front-end#22]
**Hello 👋** 
In this project we are a team of 4 divided in groups of 2 people:
- Back Bees 🐝
  - [Henry Nawrocki](https://github.com/hsztan)
  - [Emily Robertson](https://github.com/emyrue)
- Front Bees 🐝
  - [Aaron Keegan](https://github.com/AKeeganDev)
  - [Augusto Galindo](https://github.com/jsug9)

To check our Bee Ban Board [click here](https://github.com/users/jsug9/projects/6/views/1).
<img width="1440" alt="Captura de Pantalla 2022-08-11 a la(s) 1 14 11 p  m" src="https://user-images.githubusercontent.com/75434179/184210187-870a76a3-14b1-4d34-8c5e-2dedc65d30fa.png">

**Comment by MuriloRoque** [comment]
Hi @jsug9, @hsztan, @AKeeganDev, @emyrue,

Good job so far!
There are some issues that you still need to work on but you are almost there!

## Suggested changes

- [ ] Please put a screenshot of your Kanban board to this issue's description, as it says in the requirements.

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by MuriloRoque** [comment]
Hi @jsug9, @hsztan, @AKeeganDev, @emyrue,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
